packages:
  - config
  - watcher
minimumReleaseAgeExclude:
  - knip
  - "@types/node"
  - oxfmt
  - "@oxfmt/*"
  - oxlint
  - "@oxlint/*"
  - "@slack/types"
  - "@slack/web-api"
overrides:
  "@slack/types": "3.1.0"
  "@slack/web-api": "8.1.0"
allowBuilds:
  better-sqlite3: true
  esbuild: true
