export const DEFAULT_REVIEW_READY_DELAY_MS = 10 * 60 * 1_000;
export const DEFAULT_IN_REVIEW_REMINDER_AFTER_DAYS = 3;
export const DEFAULT_IN_REVIEW_REMINDER_POST_AT = "09:00";
export const DEFAULT_IN_REVIEW_REMINDER_TIME_ZONE = "Asia/Tokyo";
